include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/flutter_all.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
