name: qp_for_all
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
