name: qp_for_all
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.18.5+1
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  http: ^0.13.5
  path_provider: ^2.0.11
  pdf_render: ^1.3.4
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  printing: ^5.9.3
  riverpod_annotation: ^1.0.4
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
