name: qp_for_all
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_smart_retry: ^1.4.0
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.18.5+1
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  path_provider: ^2.0.11
  pdf_render: ^1.3.6
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  printing: ^5.9.3
  riverpod_annotation: ^1.1.1
  settings_ui: ^2.0.2
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
