// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPvaWwavEfb-voBlAOUNnLtEjyzeeE7M',
    appId: '1:7924463849:web:68e54db00152345709d878',
    messagingSenderId: '7924463849',
    projectId: 'qp-for-all',
    authDomain: 'qp-for-all.firebaseapp.com',
    storageBucket: 'qp-for-all.appspot.com',
    measurementId: 'G-X7VP45FGRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAuWoUW0rWiIinQ88gON-dMPjEp7wTBIM',
    appId: '1:7924463849:android:83eac3baa6b4e83b09d878',
    messagingSenderId: '7924463849',
    projectId: 'qp-for-all',
    storageBucket: 'qp-for-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTIHdlOLpsEyQUo1nCNbZ02KqqzvDbBY',
    appId: '1:7924463849:ios:efac30bfa4b0956b09d878',
    messagingSenderId: '7924463849',
    projectId: 'qp-for-all',
    storageBucket: 'qp-for-all.appspot.com',
    iosClientId: '7924463849-am04o7um1sdge7ktt2e365oohqg8dfvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.qpForAll',
  );
}
