on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@3
      - name: Setup flutter action
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - name: Fetch packages
        run: flutter pub get
      - name: Run tests
        run: flutter test
